export const balloonClubData = [
  // Đang cập nhật đến id số 37 & thiếu các id 20-21-22-10-29
  //     ⭐ Beginner
  // ⭐⭐ Intermediate
  // ⭐⭐⭐ Advanced
  // ⭐⭐⭐⭐ Professional
  {
    category: "🎓 Balloon Academy",
    subCategories: ["Tạo hình bong bóng", "Workshop", "Kỹ thuật & Tricks", "Lộ trình học"],
    tools: [], // Dữ liệu đang cập nhật
  },
  {
    category: "🤖 AI Tools",
    subCategories: ["AI", "Thư viện mẫu tham khảo", "Icon", "Văn phòng", "Thiết kế", "Giảm dung lượng", "Bảng màu", "Học tập", "Trò chơi"],
    tools: [
      // AI
      {
        id: 1,
        title: "Behind the Mail",
        subCategory: "AI",
        description: "Trình theo dõi email marketing và newsletter.",
        note: "Miễn phí",
        guide: "Đăng ký tài khoản ,- Theo dõi các chiến dịch email ,- Phân tích hiệu quả chiến dịch ,-",
        icon: "https://www.google.com/s2/favicons?domain=behindthemail.com",
        link: "https://behindthemail.com",
        tags: ["Marketing", "Email", "Công cụ"],
        images: [
          "https://images.unsplash.com/photo-1557200134-90327ee9fafa?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 2,
        title: "Messenger Abeto",
        subCategory: "AI",
        description: "Công cụ hỗ trợ quản lý tin nhắn hiệu quả.",
        note: "Miễn phí",
        guide: "Kết nối tài khoản Messenger ,- Thiết lập trả lời tự động ,- Quản lý tin nhắn tập trung ,-",
        icon: "https://www.google.com/s2/favicons?domain=messenger.abeto.co",
        link: "https://messenger.abeto.co",
        tags: ["Social", "Tin nhắn", "Quản lý"],
        images: [
          "https://images.unsplash.com/photo-1611746872915-47382b6068c4?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1534531173927-aeb928d54385?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 3,
        title: "Blackbox AI",
        subCategory: "AI",
        description: "Trợ lý lập trình AI hỗ trợ viết code nhanh chóng.",
        note: "Có trả phí",
        guide: "Cài đặt extension vào trình soạn thảo ,- Nhập yêu cầu bằng ngôn ngữ tự nhiên ,- Xem gợi ý code và áp dụng ,-",
        icon: "https://www.google.com/s2/favicons?domain=blackbox.ai",
        link: "https://www.blackbox.ai",
        tags: ["AI", "Lập trình", "Công cụ"],
        images: [
          "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 4,
        title: "Manific.ai",
        subCategory: "AI",
        description: "Nâng cấp chất lượng ảnh bằng AI",
        note: "Có trả phí",
        guide: "Tải ảnh lên hệ thống ,- Chọn các tùy chọn upscale mong muốn ,- Chờ AI xử lý và tải ảnh chất lượng cao về",
        icon: "https://www.google.com/s2/favicons?domain=magnific.ai",
        link: "https://magnific.ai",
        tags: ["AI", "nâng cấp ảnh", "thiết kế"],
        images: [
          "https://images.unsplash.com/photo-1620674666012-6d754b98c362?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 5,
        title: "Meigen",
        subCategory: "AI",
        description: "Công cụ tạo mã QR tùy chỉnh thiết kế.",
        note: "Có trả phí",
        guide: "Nhập nội dung hoặc link cần tạo QR ,- Tùy chỉnh màu sắc và phong cách ,- Xuất file mã QR ,-",
        icon: "https://www.google.com/s2/favicons?domain=meigen.co",
        link: "https://meigen.co",
        tags: ["QR Code", "Thiết kế", "Tiện ích"],
        images: [
          "https://images.unsplash.com/photo-1595078475328-1ab839d06d98?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1596495577886-d920f1fb7538?q=80&w=600&auto=format&fit=crop",
        ],
      },

      // Thư viện mẫu tham khảo
      {
        id: 6,
        title: "MotionBGs",
        subCategory: "Thư viện mẫu tham khảo",
        description: "Thư viện hình nền động cho website.",
        note: "Miễn phí",
        guide: "Chọn mẫu background yêu thích ,- Tùy chỉnh thông số hiển thị ,- Sao chép mã nhúng cho website ,-",
        icon: "https://www.google.com/s2/favicons?domain=motionbgs.com",
        link: "https://motionbgs.com",
        tags: ["Thiết kế", "Web", "Animation"],
        images: [
          "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1549692520-acc6669e2f0c?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 7,
        title: "Pinterest",
        subCategory: "Thư viện mẫu tham khảo",
        description: "Nền tảng tìm kiếm ý tưởng hình ảnh và thiết kế.",
        note: "Miễn phí",
        guide: "Đăng nhập tài khoản ,- Tìm kiếm từ khóa chủ đề thiết kế ,- Lưu hình ảnh vào bảng cá nhân ,-",
        icon: "https://www.google.com/s2/favicons?domain=pinterest.com",
        link: "https://www.pinterest.com",
        tags: ["Thiết kế", "Ý tưởng", "Hình ảnh"],
        images: [
          "https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1554415707-6e8dfc930260?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 8,
        title: "Unsplash",
        subCategory: "Thư viện mẫu tham khảo",
        description: "Thư viện hình ảnh chất lượng cao miễn phí.",
        note: "Miễn phí",
        guide: "Nhập từ khóa hình ảnh cần tìm ,- Chọn bức ảnh phù hợp ,- Tải về theo độ phân giải mong muốn ,-",
        icon: "https://www.google.com/s2/favicons?domain=unsplash.com",
        link: "https://unsplash.com",
        tags: ["Hình ảnh", "Thiết kế", "Nguồn tài nguyên"],
        images: [
          "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1493863641943-9b68992a8d07?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 9,
        title: "ThietkeDecor",
        subCategory: "Thư viện mẫu tham khảo",
        description: "Dịch vụ thiết kế và trang trí nội thất chuyên nghiệp.",
        note: "Có trả phí",
        guide: "Tham khảo danh mục dự án ,- Liên hệ yêu cầu tư vấn ,- Nhận báo giá thiết kế ,-",
        icon: "https://www.google.com/s2/favicons?domain=thietkedecor.vn",
        link: "https://thietkedecor.vn",
        tags: ["Thiết kế", "Decor", "Nội thất"],
        images: [
          "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=600&auto=format&fit=crop",
        ],
      },

      // Icon
      {
        id: 11,
        title: "Flaticon",
        subCategory: "Icon",
        description: "Kho biểu tượng vector khổng lồ cho thiết kế.",
        note: "Có trả phí",
        guide: "Nhập từ khóa icon cần tìm ,- Chọn biểu tượng ưa thích ,- Tải về với định dạng mong muốn ,-",
        icon: "https://www.google.com/s2/favicons?domain=flaticon.com",
        link: "https://www.flaticon.com/",
        tags: ["Icon", "Vector", "Thiết kế"],
        images: [
          "https://images.unsplash.com/photo-1572044162444-ad60f1288dea?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 12,
        title: "React Icons",
        subCategory: "Icon",
        description: "Bộ sưu tập icon cho dự án web",
        note: "Miễn phí",
        guide: "Tìm kiếm icon theo từ khóa ,- Sao chép tên icon ,- Import vào dự án React và sử dụng",
        icon: "https://www.google.com/s2/favicons?domain=react-icons.github.io",
        link: "https://react-icons.github.io/react-icons/",
        tags: ["lập trình", "icon", "UI/UX"],
        images: [
          "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=600&auto=format&fit=crop",
        ],
      },

      // Văn phòng
      {
        id: 13,
        title: "Ruflo",
        subCategory: "Văn phòng",
        description: "Giải pháp quản lý và tối ưu hóa quy trình làm việc.",
        note: "Có trả phí",
        guide: "Đăng nhập dashboard ,- Thiết lập quy tắc tự động hóa ,- Theo dõi tiến độ công việc ,-",
        icon: "https://www.google.com/s2/favicons?domain=ruflo.com",
        link: "https://ruflo.com",
        tags: ["Quản lý", "Productivity", "Workflow"],
        images: [
          "https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1506784365847-bbad939e9335?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 14,
        title: "Quenq",
        subCategory: "Văn phòng",
        description: "Công cụ quản lý câu hỏi và khảo sát trực tuyến.",
        note: "Miễn phí",
        guide: "Tạo bảng hỏi mới ,- Thêm các loại câu hỏi ,- Gửi link cho người tham gia ,-",
        icon: "https://www.google.com/s2/favicons?domain=quenq.com",
        link: "https://quenq.com",
        tags: ["Khảo sát", "Data", "Tiện ích"],
        images: [
          "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 15,
        title: "Google Flow",
        subCategory: "Văn phòng",
        description: "Nền tảng hỗ trợ phát triển quy trình làm việc.",
        note: "Miễn phí",
        guide: "Tạo dự án mới ,- Thiết lập các bước xử lý dữ liệu ,- Chạy quy trình và theo dõi ,-",
        icon: "https://www.google.com/s2/favicons?domain=google.com",
        link: "https://flow.google.com",
        tags: ["Workflow", "Productivity", "Google"],
        images: [
          "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 16,
        title: "SmallPDF",
        subCategory: "Văn phòng",
        description: "Chỉnh sửa và gộp file PDF",
        note: "Miễn phí",
        guide: "Chọn tính năng 'Gộp PDF' ,- Tải lên các file cần kết nối ,- Sắp xếp thứ tự và nhấn 'Gộp ngay'",
        icon: "https://www.google.com/s2/favicons?domain=smallpdf.com",
        link: "https://smallpdf.com/vi/merge-pdf",
        tags: ["PDF", "văn phòng", "tiện ích"],
        images: [
          "https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1618044733300-94720560a52d?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 17,
        title: "QR Gateway",
        subCategory: "Văn phòng",
        description: "Tạo và quản lý mã QR",
        note: "Miễn phí",
        guide: "Nhập link hoặc nội dung cần mã hóa ,- Tùy chỉnh màu sắc mã QR ,- Tải mã QR về máy để sử dụng",
        icon: "https://www.google.com/s2/favicons?domain=vi.qrgateway.com",
        link: "https://vi.qrgateway.com/",
        tags: ["QR", "tiện ích", "marketing"],
        images: [
          "https://images.unsplash.com/photo-1595079676339-1534801d62db?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 18,
        title: "WeTransfer",
        subCategory: "Văn phòng",
        description: "Chuyển gửi file dung lượng lớn",
        note: "Miễn phí",
        guide: "Tải file cần gửi lên trang web ,- Nhập email người nhận hoặc lấy link chia sẻ ,- Nhấn gửi",
        icon: "https://www.google.com/s2/favicons?domain=wetransfer.com",
        link: "https://wetransfer.com/",
        tags: ["file", "chia sẻ", "văn phòng"],
        images: [
          "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 19,
        title: "Piliapp Symbols",
        subCategory: "Văn phòng",
        description: "Công cụ tạo ký tự đặc biệt",
        note: "Miễn phí",
        guide: "Chọn loại ký tự (số mũ, ký hiệu) ,- Nhấp vào ký tự để sao chép ,- Dán vào nơi bạn cần sử dụng",
        icon: "https://www.google.com/s2/favicons?domain=piliapp.com",
        link: "https://www.piliapp.com/symbol/subscript-superscript/",
        tags: ["ký tự", "tiện ích", "soạn thảo"],
        images: [
          "https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=600&auto=format&fit=crop",
        ],
      },

      // Thiết kế
      {
        id: 23,
        title: "Logo Diffusion",
        subCategory: "Thiết kế",
        description: "Công cụ tạo logo bằng trí tuệ nhân tạo.",
        note: "Có trả phí",
        guide: "Nhập mô tả ý tưởng logo ,- Tùy chỉnh các gợi ý AI đưa ra ,- Tải file logo hoàn thiện ,-",
        icon: "https://www.google.com/s2/favicons?domain=logodiffusion.com",
        link: "https://logodiffusion.com",
        tags: ["AI", "Thiết kế", "Logo"],
        images: [
          "https://images.unsplash.com/photo-1626785774573-4b799315347d?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1634942539454-9493921b7475?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 24,
        title: "ThemeDevHub",
        subCategory: "Thiết kế",
        description: "Nơi cung cấp các giao diện website chất lượng.",
        note: "Có trả phí",
        guide: "Tìm kiếm chủ đề theo danh mục ,- Xem trước giao diện trực tiếp ,- Mua hoặc tải xuống theo yêu cầu ,-",
        icon: "https://www.google.com/s2/favicons?domain=themedevhub.com",
        link: "https://www.themedevhub.com/themes",
        tags: ["Theme", "Website", "Thiết kế"],
        images: [
          "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1547658719-da2b51169165?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 25,
        title: "Barcode Generator",
        subCategory: "Thiết kế",
        description: "Tạo mã vạch chuyên nghiệp trực tuyến.",
        note: "Miễn phí",
        guide: "Nhập dữ liệu vào ô trống ,- Chọn loại mã vạch phù hợp ,- Tùy chỉnh kích thước và tải về ,-",
        icon: "https://www.google.com/s2/favicons?domain=barcode.tec-it.com",
        link: "https://barcode.tec-it.com/en/EAN13",
        tags: ["Barcode", "Công cụ", "Tiện ích"],
        images: [
          "https://images.unsplash.com/photo-1589758438368-0863920c7414?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1595078475328-1ab839d06d98?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 26,
        title: "Font Lnth",
        subCategory: "Thiết kế",
        description: "Tìm kiếm và tạo phông chữ",
        note: "Miễn phí",
        guide: "Nhập nội dung cần hiển thị ,- Chọn kiểu font bạn ưng ý ,- Copy đoạn văn bản đã tạo font",
        icon: "https://www.google.com/s2/favicons?domain=fontlnth.com",
        link: "https://fontlnth.com/",
        tags: ["font", "thiết kế", " typography"],
        images: [
          "https://images.unsplash.com/photo-1626785774573-4b799315347d?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 27,
        title: "Kapwing",
        subCategory: "Thiết kế",
        description: "Chỉnh sửa video trực tuyến",
        note: "Miễn phí & trả phí",
        guide: "Tải video lên trình duyệt ,- Sử dụng công cụ cắt, ghép hoặc thêm chữ ,- Xuất video hoàn chỉnh",
        icon: "https://www.google.com/s2/favicons?domain=kapwing.com",
        link: "https://www.kapwing.com/",
        tags: ["video", "chỉnh sửa", "content"],
        images: [
          "https://images.unsplash.com/photo-1574928066524-74c05f778d9b?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 28,
        title: "Pacdora",
        subCategory: "Thiết kế",
        description: "Thiết kế bao bì 3D trực tuyến",
        note: "Miễn phí & trả phí",
        guide: "Chọn mẫu bao bì có sẵn ,- Tải thiết kế 2D của bạn lên ,- Xem trước và xuất file 3D",
        icon: "https://www.google.com/s2/favicons?domain=pacdora.com",
        link: "https://www.pacdora.com/",
        tags: ["bao bì", "3D", "thiết kế"],
        images: [
          "https://images.unsplash.com/photo-1621351187462-817c76891040?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1596464406190-2581699741b2?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 30,
        title: "Adobe Color",
        subCategory: "Thiết kế",
        description: "Phối màu chuyên nghiệp",
        icon: "https://www.google.com/s2/favicons?domain=color.adobe.com",
        link: "https://color.adobe.com",
        tags: ["màu sắc", "phối màu", "thiết kế"],
        images: [
          "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1543269664-56d93c1b41a6?q=80&w=600&auto=format&fit=crop",
        ],
      },

      // Giảm dung lượng
      {
        id: 31,
        title: "Image Compressor",
        subCategory: "Giảm dung lượng",
        description: "Nén dung lượng ảnh không giảm chất lượng",
        note: "Miễn phí",
        guide: "Kéo thả ảnh cần nén vào vùng làm việc ,- Chọn mức độ nén mong muốn ,- Tải ảnh đã nén về máy",
        icon: "https://www.google.com/s2/favicons?domain=websiteplanet.com",
        link: "https://www.websiteplanet.com/vi/webtools/imagecompressor/",
        tags: ["tối ưu ảnh", "công cụ web", "tốc độ"],
        images: [
          "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1520607162513-77105b2c404d?q=80&w=600&auto=format&fit=crop",
        ],
      },

      // Bảng màu
      {
        id: 32,
        title: "CSS Gradient",
        subCategory: "Bảng màu",
        description: "Công cụ tạo mã màu gradient CSS đẹp mắt.",
        note: "Miễn phí",
        guide: "Chọn các dải màu yêu thích ,- Điều chỉnh góc và độ chuyển màu ,- Sao chép mã CSS để sử dụng ,-",
        icon: "https://www.google.com/s2/favicons?domain=cssgradient.io",
        link: "https://cssgradient.io/gradient-backgrounds/",
        tags: ["CSS", "Thiết kế", "Front-end"],
        images: [
          "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1557683316-973673baf926?q=80&w=600&auto=format&fit=crop",
        ],
      },

      // Học tập
      {
        id: 33,
        title: "Class Central",
        subCategory: "Học tập",
        description: "Nền tảng tổng hợp các khóa học trực tuyến miễn phí.",
        note: "Miễn phí",
        guide: "Tìm kiếm chủ đề học tập ,- Chọn khóa học từ danh sách ,- Bắt đầu học theo lộ trình ,-",
        icon: "https://www.google.com/s2/favicons?domain=classcentral.com",
        link: "https://www.classcentral.com",
        tags: ["Giáo dục", "Học tập", "Khóa học"],
        images: [
          "https://images.unsplash.com/photo-1501349800519-48096d60b5a3?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 34,
        title: "MuscleWiki",
        subCategory: "Học tập",
        description: "Cơ sở dữ liệu các bài tập gym theo từng nhóm cơ.",
        note: "Miễn phí",
        guide: "Chọn nhóm cơ bạn muốn tập ,- Xem danh sách bài tập gợi ý ,- Làm theo hướng dẫn video ,-",
        icon: "https://www.google.com/s2/favicons?domain=musclewiki.com",
        link: "https://musclewiki.com",
        tags: ["Sức khỏe", "Fitness", "Thể thao"],
        images: [
          "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1594882645126-14020914d58d?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 35,
        title: "Project Gutenberg",
        subCategory: "Học tập",
        description: "Kho thư viện sách điện tử miễn phí bản quyền.",
        note: "Miễn phí",
        guide: "Tìm kiếm tên sách hoặc tác giả ,- Chọn định dạng tải về ,- Đọc trên thiết bị cá nhân ,-",
        icon: "https://www.google.com/s2/favicons?domain=gutenberg.org",
        link: "https://www.gutenberg.org",
        tags: ["Sách", "Giáo dục", "Tài liệu"],
        images: [
          "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=600&auto=format&fit=crop",
        ],
      },

      // Trò chơi
      {
        id: 36,
        title: "Quayso.vn",
        subCategory: "Trò chơi",
        description: "Công cụ quay số may mắn trực tuyến cho sự kiện.",
        note: "Miễn phí",
        guide:
          "Nhập danh sách người tham gia ,- Hoặc nhập hình phạt trên bàn nhậu ,- Cấu hình số lượng giải thưởng ,- Bấm quay số để xác định kết quả ,-",
        icon: "https://www.google.com/s2/favicons?domain=quayso.vn",
        link: "https://quayso.vn",
        tags: ["Sự kiện", "Tiện ích", "Game"],
        images: [
          "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=600&auto=format&fit=crop",
        ],
      },
      {
        id: 37,
        title: "Akinator (Tiếng Việt)",
        subCategory: "Trò chơi",
        description: "Game giải trí đoán nhân vật thông qua câu hỏi.",
        note: "Miễn phí",
        guide: "Nghĩ về một nhân vật trong đầu ,- Trả lời các câu hỏi của Akinator ,- Chờ máy tính đoán đúng tên ,-",
        icon: "https://www.google.com/s2/favicons?domain=vi.akinator.com",
        link: "https://vi.akinator.com",
        tags: ["Game", "Giải trí", "AI"],
        images: [
          "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=600&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=600&auto=format&fit=crop",
        ],
      },
    ],
  },
  {
    category: "🤝 Success Stories",
    subCategories: ["Trường mầm non", "Hệ thống thức ăn nhanh", "Hệ thống nhà hàng", "Trung tâm thương mại"],
    tools: [], // Dữ liệu đang cập nhật
  },
];
